targets:
  $default:
    builders:
      freezed:
        options:
          # Generated classes stay private to their library; we expose hand-written APIs.
          copy_with: true
          equal: true
          to_string: true
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
          include_if_null: false
          create_factory: true
          create_to_json: true
